<div class="navbar navbar-custom">
	<div class="navbar-inner navbar-inner-custom" id="header">
    	<div class="container container-main">
            <!-- <span class="icon-plane-top pull-left"></span> --><h2 class="brand brand-custom"><?php echo Enum_System::SYSTEM_NAME;?></h2>
            <div class="btn-group pull-right">
            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><?php echo $headerInfo['userName'];?><span class="caret"></span></button>
            <ul class="dropdown-menu">
            <!-- <li><a href="#">修改密码</a></li>
            <li class="divider"></li> -->
            <li><a href="/Login/logout">登出</a></li>
            </ul>
            </div>
            <ul class="nav pull-right">
            <li><p class="navbar-text text-custom">OTA：<?php echo $headerInfo['partnerName'];?></p></li>
            <li class="divider-vertical divider-vertical-custom"></li>
            <li><p class="navbar-text text-custom">欢迎</p></li>
            </ul>
        </div>
    </div>
</div> 
