<meta charset="utf-8">
<title><?php echo Enum_System::SYSTEM_NAME;?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain'];?>css/bootstrap.css" />
<script src="<?php echo $webConfig['imgDomain'];?>js/lib/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain'];?>js/lib/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain'];?>js/common/modalfix.js" type="text/javascript"></script> 
<!--[if lte IE 6]>
<script type="text/javascript" src="<?php echo $webConfig['imgDomain'];?>js/lib/bootstrap-ie.js"></script>
<![endif]-->
<!--[if lte IE 6]>
<link rel="stylesheet" type="text/css" href="<?php echo $webConfig['imgDomain'];?>css/bootstrap-ie6.css">
<![endif]-->
<!--[if lte IE 7]>
<link rel="stylesheet" type="text/css" href="<?php echo $webConfig['imgDomain'];?>css/ie.css">
<![endif]-->
<!--[if lte IE 7]>
<div class="alert alert-error">
<button data-dismiss="alert" class="close" type="button">×</button>
您使用的浏览器版本太低，为了能有更好的操作体验，建议您升级到 <a href="http://www.microsoft.com/china/windows/internet-explorer/" target="_blank">Internet Explorer 10</a> 或以下浏览器： <a href="http://www.mozillaonline.com/">Firefox</a> / <a href="http://www.google.com/chrome/?hl=zh-CN">Chrome</a> / <a href="http://www.apple.com.cn/safari/">Safari</a> / <a href="http://www.operachina.com/">Opera</a>

</div>
<![endif]-->
<link href="<?php echo $webConfig['imgDomain'];?>css/css.css" rel="stylesheet">
